/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in normal development. It is committed so
// the empty workspace has a complete TypeScript shape before dependencies exist.
